package net.minecraft.util.datafix;

import com.google.common.collect.ImmutableMap;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.schemas.Schema;
import java.util.Objects;
import java.util.function.BiFunction;
import java.util.function.Function;
import net.minecraft.SharedConstants;
import net.minecraft.Util;
import net.minecraft.util.datafix.OminousBannerBlockEntityRenameFix;
import net.minecraft.util.datafix.OminousBannerRenameFix;
import net.minecraft.util.datafix.fixes.AddNewChoices;
import net.minecraft.util.datafix.fixes.AdvancementsFix;
import net.minecraft.util.datafix.fixes.BedBlockEntityInjecter;
import net.minecraft.util.datafix.fixes.BedItemColorFix;
import net.minecraft.util.datafix.fixes.BiomeFix;
import net.minecraft.util.datafix.fixes.BlockEntityBannerColorFix;
import net.minecraft.util.datafix.fixes.BlockEntityBlockStateFix;
import net.minecraft.util.datafix.fixes.BlockEntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.BlockEntityIdFix;
import net.minecraft.util.datafix.fixes.BlockEntityJukeboxFix;
import net.minecraft.util.datafix.fixes.BlockEntityKeepPacked;
import net.minecraft.util.datafix.fixes.BlockEntityShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignTextStrictJsonFix;
import net.minecraft.util.datafix.fixes.BlockNameFlatteningFix;
import net.minecraft.util.datafix.fixes.BlockRenameFix;
import net.minecraft.util.datafix.fixes.BlockStateStructureTemplateFix;
import net.minecraft.util.datafix.fixes.CatTypeFix;
import net.minecraft.util.datafix.fixes.ChunkLightRemoveFix;
import net.minecraft.util.datafix.fixes.ChunkPalettedStorageFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix2;
import net.minecraft.util.datafix.fixes.ChunkStructuresTemplateRenameFix;
import net.minecraft.util.datafix.fixes.ChunkToProtochunkFix;
import net.minecraft.util.datafix.fixes.ColorlessShulkerEntityFix;
import net.minecraft.util.datafix.fixes.DyeItemRenameFix;
import net.minecraft.util.datafix.fixes.EntityArmorStandSilentFix;
import net.minecraft.util.datafix.fixes.EntityBlockStateFix;
import net.minecraft.util.datafix.fixes.EntityCatSplitFix;
import net.minecraft.util.datafix.fixes.EntityCodSalmonFix;
import net.minecraft.util.datafix.fixes.EntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.EntityElderGuardianSplitFix;
import net.minecraft.util.datafix.fixes.EntityEquipmentToArmorAndHandFix;
import net.minecraft.util.datafix.fixes.EntityHealthFix;
import net.minecraft.util.datafix.fixes.EntityHorseSaddleFix;
import net.minecraft.util.datafix.fixes.EntityHorseSplitFix;
import net.minecraft.util.datafix.fixes.EntityIdFix;
import net.minecraft.util.datafix.fixes.EntityItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityMinecartIdentifiersFix;
import net.minecraft.util.datafix.fixes.EntityPaintingItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityPaintingMotiveFix;
import net.minecraft.util.datafix.fixes.EntityPufferfishRenameFix;
import net.minecraft.util.datafix.fixes.EntityRavagerRenameFix;
import net.minecraft.util.datafix.fixes.EntityRedundantChanceTagsFix;
import net.minecraft.util.datafix.fixes.EntityRidingToPassengersFix;
import net.minecraft.util.datafix.fixes.EntityShulkerColorFix;
import net.minecraft.util.datafix.fixes.EntitySkeletonSplitFix;
import net.minecraft.util.datafix.fixes.EntityStringUuidFix;
import net.minecraft.util.datafix.fixes.EntityTheRenameningFix;
import net.minecraft.util.datafix.fixes.EntityTippedArrowFix;
import net.minecraft.util.datafix.fixes.EntityWolfColorFix;
import net.minecraft.util.datafix.fixes.EntityZombieSplitFix;
import net.minecraft.util.datafix.fixes.EntityZombieVillagerTypeFix;
import net.minecraft.util.datafix.fixes.HeightmapRenamingFix;
import net.minecraft.util.datafix.fixes.IglooMetadataRemovalFix;
import net.minecraft.util.datafix.fixes.ItemBannerColorFix;
import net.minecraft.util.datafix.fixes.ItemCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.ItemIdFix;
import net.minecraft.util.datafix.fixes.ItemLoreFix;
import net.minecraft.util.datafix.fixes.ItemPotionFix;
import net.minecraft.util.datafix.fixes.ItemRenameFix;
import net.minecraft.util.datafix.fixes.ItemShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.ItemSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackEnchantmentNamesFix;
import net.minecraft.util.datafix.fixes.ItemStackMapIdFix;
import net.minecraft.util.datafix.fixes.ItemStackSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackTheFlatteningFix;
import net.minecraft.util.datafix.fixes.ItemWaterPotionFix;
import net.minecraft.util.datafix.fixes.ItemWrittenBookPagesStrictJsonFix;
import net.minecraft.util.datafix.fixes.LeavesFix;
import net.minecraft.util.datafix.fixes.LevelDataGeneratorOptionsFix;
import net.minecraft.util.datafix.fixes.LevelFlatGeneratorInfoFix;
import net.minecraft.util.datafix.fixes.MapIdFix;
import net.minecraft.util.datafix.fixes.MobSpawnerEntityIdentifiersFix;
import net.minecraft.util.datafix.fixes.NamedEntityFix;
import net.minecraft.util.datafix.fixes.NewVillageFix;
import net.minecraft.util.datafix.fixes.ObjectiveDisplayNameFix;
import net.minecraft.util.datafix.fixes.ObjectiveRenderTypeFix;
import net.minecraft.util.datafix.fixes.OptionsAddTextBackgroundFix;
import net.minecraft.util.datafix.fixes.OptionsForceVBOFix;
import net.minecraft.util.datafix.fixes.OptionsKeyLwjgl3Fix;
import net.minecraft.util.datafix.fixes.OptionsKeyTranslationFix;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguageFix;
import net.minecraft.util.datafix.fixes.RecipesFix;
import net.minecraft.util.datafix.fixes.RecipesRenameningFix;
import net.minecraft.util.datafix.fixes.References;
import net.minecraft.util.datafix.fixes.RenamedCoralFansFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFix;
import net.minecraft.util.datafix.fixes.ReorganizePoi;
import net.minecraft.util.datafix.fixes.SavedDataVillageCropFix;
import net.minecraft.util.datafix.fixes.StatsCounterFix;
import net.minecraft.util.datafix.fixes.SwimStatsRenameFix;
import net.minecraft.util.datafix.fixes.TeamDisplayNameFix;
import net.minecraft.util.datafix.fixes.TrappedChestBlockEntityFix;
import net.minecraft.util.datafix.fixes.VillagerDataFix;
import net.minecraft.util.datafix.fixes.VillagerRebuildLevelAndXpFix;
import net.minecraft.util.datafix.fixes.VillagerTradeFix;
import net.minecraft.util.datafix.fixes.WriteAndReadFix;
import net.minecraft.util.datafix.fixes.ZombieVillagerRebuildXpFix;
import net.minecraft.util.datafix.schemas.NamespacedSchema;
import net.minecraft.util.datafix.schemas.V100;
import net.minecraft.util.datafix.schemas.V102;
import net.minecraft.util.datafix.schemas.V1022;
import net.minecraft.util.datafix.schemas.V106;
import net.minecraft.util.datafix.schemas.V107;
import net.minecraft.util.datafix.schemas.V1125;
import net.minecraft.util.datafix.schemas.V135;
import net.minecraft.util.datafix.schemas.V143;
import net.minecraft.util.datafix.schemas.V1451;
import net.minecraft.util.datafix.schemas.V1451_1;
import net.minecraft.util.datafix.schemas.V1451_2;
import net.minecraft.util.datafix.schemas.V1451_3;
import net.minecraft.util.datafix.schemas.V1451_4;
import net.minecraft.util.datafix.schemas.V1451_5;
import net.minecraft.util.datafix.schemas.V1451_6;
import net.minecraft.util.datafix.schemas.V1451_7;
import net.minecraft.util.datafix.schemas.V1460;
import net.minecraft.util.datafix.schemas.V1466;
import net.minecraft.util.datafix.schemas.V1470;
import net.minecraft.util.datafix.schemas.V1481;
import net.minecraft.util.datafix.schemas.V1483;
import net.minecraft.util.datafix.schemas.V1486;
import net.minecraft.util.datafix.schemas.V1510;
import net.minecraft.util.datafix.schemas.V1800;
import net.minecraft.util.datafix.schemas.V1801;
import net.minecraft.util.datafix.schemas.V1904;
import net.minecraft.util.datafix.schemas.V1906;
import net.minecraft.util.datafix.schemas.V1909;
import net.minecraft.util.datafix.schemas.V1920;
import net.minecraft.util.datafix.schemas.V1928;
import net.minecraft.util.datafix.schemas.V1929;
import net.minecraft.util.datafix.schemas.V1931;
import net.minecraft.util.datafix.schemas.V501;
import net.minecraft.util.datafix.schemas.V700;
import net.minecraft.util.datafix.schemas.V701;
import net.minecraft.util.datafix.schemas.V702;
import net.minecraft.util.datafix.schemas.V703;
import net.minecraft.util.datafix.schemas.V704;
import net.minecraft.util.datafix.schemas.V705;
import net.minecraft.util.datafix.schemas.V808;
import net.minecraft.util.datafix.schemas.V99;

public class DataFixers {
   private static final BiFunction SAME = Schema::<init>;
   private static final BiFunction SAME_NAMESPACED = NamespacedSchema::<init>;
   private static final DataFixer DATA_FIXER = createFixerUpper();

   private static DataFixer createFixerUpper() {
      DataFixerBuilder var0 = new DataFixerBuilder(SharedConstants.getCurrentVersion().getWorldVersion());
      addFixers(var0);
      return var0.build(Util.backgroundExecutor());
   }

   public static DataFixer getDataFixer() {
      return DATA_FIXER;
   }

   private static void addFixers(DataFixerBuilder dataFixerBuilder) {
      Schema var1 = dataFixerBuilder.addSchema(99, V99::<init>);
      Schema var2 = dataFixerBuilder.addSchema(100, V100::<init>);
      dataFixerBuilder.addFixer(new EntityEquipmentToArmorAndHandFix(var2, true));
      Schema var3 = dataFixerBuilder.addSchema(101, SAME);
      dataFixerBuilder.addFixer(new BlockEntitySignTextStrictJsonFix(var3, false));
      Schema var4 = dataFixerBuilder.addSchema(102, V102::<init>);
      dataFixerBuilder.addFixer(new ItemIdFix(var4, true));
      dataFixerBuilder.addFixer(new ItemPotionFix(var4, false));
      Schema var5 = dataFixerBuilder.addSchema(105, SAME);
      dataFixerBuilder.addFixer(new ItemSpawnEggFix(var5, true));
      Schema var6 = dataFixerBuilder.addSchema(106, V106::<init>);
      dataFixerBuilder.addFixer(new MobSpawnerEntityIdentifiersFix(var6, true));
      Schema var7 = dataFixerBuilder.addSchema(107, V107::<init>);
      dataFixerBuilder.addFixer(new EntityMinecartIdentifiersFix(var7, true));
      Schema var8 = dataFixerBuilder.addSchema(108, SAME);
      dataFixerBuilder.addFixer(new EntityStringUuidFix(var8, true));
      Schema var9 = dataFixerBuilder.addSchema(109, SAME);
      dataFixerBuilder.addFixer(new EntityHealthFix(var9, true));
      Schema var10 = dataFixerBuilder.addSchema(110, SAME);
      dataFixerBuilder.addFixer(new EntityHorseSaddleFix(var10, true));
      Schema var11 = dataFixerBuilder.addSchema(111, SAME);
      dataFixerBuilder.addFixer(new EntityPaintingItemFrameDirectionFix(var11, true));
      Schema var12 = dataFixerBuilder.addSchema(113, SAME);
      dataFixerBuilder.addFixer(new EntityRedundantChanceTagsFix(var12, true));
      Schema var13 = dataFixerBuilder.addSchema(135, V135::<init>);
      dataFixerBuilder.addFixer(new EntityRidingToPassengersFix(var13, true));
      Schema var14 = dataFixerBuilder.addSchema(143, V143::<init>);
      dataFixerBuilder.addFixer(new EntityTippedArrowFix(var14, true));
      Schema var15 = dataFixerBuilder.addSchema(147, SAME);
      dataFixerBuilder.addFixer(new EntityArmorStandSilentFix(var15, true));
      Schema var16 = dataFixerBuilder.addSchema(165, SAME);
      dataFixerBuilder.addFixer(new ItemWrittenBookPagesStrictJsonFix(var16, true));
      Schema var17 = dataFixerBuilder.addSchema(501, V501::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var17, "Add 1.10 entities fix", References.ENTITY));
      Schema var18 = dataFixerBuilder.addSchema(502, SAME);
      dataFixerBuilder.addFixer(ItemRenameFix.create(var18, "cooked_fished item renamer", (string) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(string), "minecraft:cooked_fished")?"minecraft:cooked_fish":string;
      }));
      dataFixerBuilder.addFixer(new EntityZombieVillagerTypeFix(var18, false));
      Schema var19 = dataFixerBuilder.addSchema(505, SAME);
      dataFixerBuilder.addFixer(new OptionsForceVBOFix(var19, false));
      Schema var20 = dataFixerBuilder.addSchema(700, V700::<init>);
      dataFixerBuilder.addFixer(new EntityElderGuardianSplitFix(var20, true));
      Schema var21 = dataFixerBuilder.addSchema(701, V701::<init>);
      dataFixerBuilder.addFixer(new EntitySkeletonSplitFix(var21, true));
      Schema var22 = dataFixerBuilder.addSchema(702, V702::<init>);
      dataFixerBuilder.addFixer(new EntityZombieSplitFix(var22, true));
      Schema var23 = dataFixerBuilder.addSchema(703, V703::<init>);
      dataFixerBuilder.addFixer(new EntityHorseSplitFix(var23, true));
      Schema var24 = dataFixerBuilder.addSchema(704, V704::<init>);
      dataFixerBuilder.addFixer(new BlockEntityIdFix(var24, true));
      Schema var25 = dataFixerBuilder.addSchema(705, V705::<init>);
      dataFixerBuilder.addFixer(new EntityIdFix(var25, true));
      Schema var26 = dataFixerBuilder.addSchema(804, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ItemBannerColorFix(var26, true));
      Schema var27 = dataFixerBuilder.addSchema(806, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ItemWaterPotionFix(var27, false));
      Schema var28 = dataFixerBuilder.addSchema(808, V808::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var28, "added shulker box", References.BLOCK_ENTITY));
      Schema var29 = dataFixerBuilder.addSchema(808, 1, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new EntityShulkerColorFix(var29, false));
      Schema var30 = dataFixerBuilder.addSchema(813, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ItemShulkerBoxColorFix(var30, false));
      dataFixerBuilder.addFixer(new BlockEntityShulkerBoxColorFix(var30, false));
      Schema var31 = dataFixerBuilder.addSchema(816, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OptionsLowerCaseLanguageFix(var31, false));
      Schema var32 = dataFixerBuilder.addSchema(820, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(ItemRenameFix.create(var32, "totem item renamer", (string) -> {
         return Objects.equals(string, "minecraft:totem")?"minecraft:totem_of_undying":string;
      }));
      Schema var33 = dataFixerBuilder.addSchema(1022, V1022::<init>);
      dataFixerBuilder.addFixer(new WriteAndReadFix(var33, "added shoulder entities to players", References.PLAYER));
      Schema var34 = dataFixerBuilder.addSchema(1125, V1125::<init>);
      dataFixerBuilder.addFixer(new BedBlockEntityInjecter(var34, true));
      dataFixerBuilder.addFixer(new BedItemColorFix(var34, false));
      Schema var35 = dataFixerBuilder.addSchema(1344, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OptionsKeyLwjgl3Fix(var35, false));
      Schema var36 = dataFixerBuilder.addSchema(1446, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OptionsKeyTranslationFix(var36, false));
      Schema var37 = dataFixerBuilder.addSchema(1450, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new BlockStateStructureTemplateFix(var37, false));
      Schema var38 = dataFixerBuilder.addSchema(1451, V1451::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var38, "AddTrappedChestFix", References.BLOCK_ENTITY));
      Schema var39 = dataFixerBuilder.addSchema(1451, 1, V1451_1::<init>);
      dataFixerBuilder.addFixer(new ChunkPalettedStorageFix(var39, true));
      Schema var40 = dataFixerBuilder.addSchema(1451, 2, V1451_2::<init>);
      dataFixerBuilder.addFixer(new BlockEntityBlockStateFix(var40, true));
      Schema var41 = dataFixerBuilder.addSchema(1451, 3, V1451_3::<init>);
      dataFixerBuilder.addFixer(new EntityBlockStateFix(var41, true));
      dataFixerBuilder.addFixer(new ItemStackMapIdFix(var41, false));
      Schema var42 = dataFixerBuilder.addSchema(1451, 4, V1451_4::<init>);
      dataFixerBuilder.addFixer(new BlockNameFlatteningFix(var42, true));
      dataFixerBuilder.addFixer(new ItemStackTheFlatteningFix(var42, false));
      Schema var43 = dataFixerBuilder.addSchema(1451, 5, V1451_5::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var43, "RemoveNoteBlockFlowerPotFix", References.BLOCK_ENTITY));
      dataFixerBuilder.addFixer(new ItemStackSpawnEggFix(var43, false));
      dataFixerBuilder.addFixer(new EntityWolfColorFix(var43, false));
      dataFixerBuilder.addFixer(new BlockEntityBannerColorFix(var43, false));
      dataFixerBuilder.addFixer(new LevelFlatGeneratorInfoFix(var43, false));
      Schema var44 = dataFixerBuilder.addSchema(1451, 6, V1451_6::<init>);
      dataFixerBuilder.addFixer(new StatsCounterFix(var44, true));
      dataFixerBuilder.addFixer(new BlockEntityJukeboxFix(var44, false));
      Schema var45 = dataFixerBuilder.addSchema(1451, 7, V1451_7::<init>);
      dataFixerBuilder.addFixer(new SavedDataVillageCropFix(var45, true));
      Schema var46 = dataFixerBuilder.addSchema(1451, 7, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new VillagerTradeFix(var46, false));
      Schema var47 = dataFixerBuilder.addSchema(1456, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new EntityItemFrameDirectionFix(var47, false));
      Schema var48 = dataFixerBuilder.addSchema(1458, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new EntityCustomNameToComponentFix(var48, false));
      dataFixerBuilder.addFixer(new ItemCustomNameToComponentFix(var48, false));
      dataFixerBuilder.addFixer(new BlockEntityCustomNameToComponentFix(var48, false));
      Schema var49 = dataFixerBuilder.addSchema(1460, V1460::<init>);
      dataFixerBuilder.addFixer(new EntityPaintingMotiveFix(var49, false));
      Schema var50 = dataFixerBuilder.addSchema(1466, V1466::<init>);
      dataFixerBuilder.addFixer(new ChunkToProtochunkFix(var50, true));
      Schema var51 = dataFixerBuilder.addSchema(1470, V1470::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var51, "Add 1.13 entities fix", References.ENTITY));
      Schema var52 = dataFixerBuilder.addSchema(1474, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ColorlessShulkerEntityFix(var52, false));
      dataFixerBuilder.addFixer(BlockRenameFix.create(var52, "Colorless shulker block fixer", (string) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(string), "minecraft:purple_shulker_box")?"minecraft:shulker_box":string;
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var52, "Colorless shulker item fixer", (string) -> {
         return Objects.equals(NamespacedSchema.ensureNamespaced(string), "minecraft:purple_shulker_box")?"minecraft:shulker_box":string;
      }));
      Schema var53 = dataFixerBuilder.addSchema(1475, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var53, "Flowing fixer", (string) -> {
         return (String)ImmutableMap.of("minecraft:flowing_water", "minecraft:water", "minecraft:flowing_lava", "minecraft:lava").getOrDefault(string, string);
      }));
      Schema var54 = dataFixerBuilder.addSchema(1480, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var54, "Rename coral blocks", (string) -> {
         return (String)RenamedCoralFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var54, "Rename coral items", (string) -> {
         return (String)RenamedCoralFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      Schema var55 = dataFixerBuilder.addSchema(1481, V1481::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var55, "Add conduit", References.BLOCK_ENTITY));
      Schema var56 = dataFixerBuilder.addSchema(1483, V1483::<init>);
      dataFixerBuilder.addFixer(new EntityPufferfishRenameFix(var56, true));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var56, "Rename pufferfish egg item", (string) -> {
         return (String)EntityPufferfishRenameFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      Schema var57 = dataFixerBuilder.addSchema(1484, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(ItemRenameFix.create(var57, "Rename seagrass items", (string) -> {
         return (String)ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass").getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(BlockRenameFix.create(var57, "Rename seagrass blocks", (string) -> {
         return (String)ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass").getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(new HeightmapRenamingFix(var57, false));
      Schema var58 = dataFixerBuilder.addSchema(1486, V1486::<init>);
      dataFixerBuilder.addFixer(new EntityCodSalmonFix(var58, true));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var58, "Rename cod/salmon egg items", (string) -> {
         return (String)EntityCodSalmonFix.RENAMED_EGG_IDS.getOrDefault(string, string);
      }));
      Schema var59 = dataFixerBuilder.addSchema(1487, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(ItemRenameFix.create(var59, "Rename prismarine_brick(s)_* blocks", (string) -> {
         return (String)ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs").getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(BlockRenameFix.create(var59, "Rename prismarine_brick(s)_* items", (string) -> {
         return (String)ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs").getOrDefault(string, string);
      }));
      final Schema var60 = dataFixerBuilder.addSchema(1488, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var60, "Rename kelp/kelptop", (string) -> {
         return (String)ImmutableMap.of("minecraft:kelp_top", "minecraft:kelp", "minecraft:kelp", "minecraft:kelp_plant").getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var60, "Rename kelptop", (string) -> {
         return Objects.equals(string, "minecraft:kelp_top")?"minecraft:kelp":string;
      }));
      dataFixerBuilder.addFixer(new NamedEntityFix(var60, false, "Command block block entity custom name fix", References.BLOCK_ENTITY, "minecraft:command_block") {
         protected Typed fix(Typed typed) {
            return typed.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      dataFixerBuilder.addFixer(new NamedEntityFix(var60, false, "Command block minecart custom name fix", References.ENTITY, "minecraft:commandblock_minecart") {
         protected Typed fix(Typed typed) {
            return typed.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      dataFixerBuilder.addFixer(new IglooMetadataRemovalFix(var60, false));
      Schema var61 = dataFixerBuilder.addSchema(1490, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var61, "Rename melon_block", (string) -> {
         return Objects.equals(string, "minecraft:melon_block")?"minecraft:melon":string;
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var61, "Rename melon_block/melon/speckled_melon", (string) -> {
         return (String)ImmutableMap.of("minecraft:melon_block", "minecraft:melon", "minecraft:melon", "minecraft:melon_slice", "minecraft:speckled_melon", "minecraft:glistering_melon_slice").getOrDefault(string, string);
      }));
      Schema var62 = dataFixerBuilder.addSchema(1492, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ChunkStructuresTemplateRenameFix(var62, false));
      Schema var63 = dataFixerBuilder.addSchema(1494, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ItemStackEnchantmentNamesFix(var63, false));
      Schema var64 = dataFixerBuilder.addSchema(1496, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new LeavesFix(var64, false));
      Schema var65 = dataFixerBuilder.addSchema(1500, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new BlockEntityKeepPacked(var65, false));
      Schema var66 = dataFixerBuilder.addSchema(1501, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new AdvancementsFix(var66, false));
      Schema var67 = dataFixerBuilder.addSchema(1502, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new RecipesFix(var67, false));
      Schema var68 = dataFixerBuilder.addSchema(1506, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new LevelDataGeneratorOptionsFix(var68, false));
      Schema var69 = dataFixerBuilder.addSchema(1508, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new BiomeFix(var69, false));
      Schema var70 = dataFixerBuilder.addSchema(1510, V1510::<init>);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var70, "Block renamening fix", (string) -> {
         return (String)EntityTheRenameningFix.RENAMED_BLOCKS.getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var70, "Item renamening fix", (string) -> {
         return (String)EntityTheRenameningFix.RENAMED_ITEMS.getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(new RecipesRenameningFix(var70, false));
      dataFixerBuilder.addFixer(new EntityTheRenameningFix(var70, true));
      dataFixerBuilder.addFixer(new SwimStatsRenameFix(var70, false));
      Schema var71 = dataFixerBuilder.addSchema(1514, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ObjectiveDisplayNameFix(var71, false));
      dataFixerBuilder.addFixer(new TeamDisplayNameFix(var71, false));
      dataFixerBuilder.addFixer(new ObjectiveRenderTypeFix(var71, false));
      Schema var72 = dataFixerBuilder.addSchema(1515, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var72, "Rename coral fan blocks", (string) -> {
         return (String)RenamedCoralFansFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      Schema var73 = dataFixerBuilder.addSchema(1624, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new TrappedChestBlockEntityFix(var73, false));
      Schema var74 = dataFixerBuilder.addSchema(1800, V1800::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var74, "Added 1.14 mobs fix", References.ENTITY));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var74, "Rename dye items", (string) -> {
         return (String)DyeItemRenameFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      Schema var75 = dataFixerBuilder.addSchema(1801, V1801::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var75, "Added Illager Beast", References.ENTITY));
      Schema var76 = dataFixerBuilder.addSchema(1802, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(BlockRenameFix.create(var76, "Rename sign blocks & stone slabs", (string) -> {
         return (String)ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign", "minecraft:wall_sign", "minecraft:oak_wall_sign").getOrDefault(string, string);
      }));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var76, "Rename sign item & stone slabs", (string) -> {
         return (String)ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign").getOrDefault(string, string);
      }));
      Schema var77 = dataFixerBuilder.addSchema(1803, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ItemLoreFix(var77, false));
      Schema var78 = dataFixerBuilder.addSchema(1904, V1904::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var78, "Added Cats", References.ENTITY));
      dataFixerBuilder.addFixer(new EntityCatSplitFix(var78, false));
      Schema var79 = dataFixerBuilder.addSchema(1905, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ChunkStatusFix(var79, false));
      Schema var80 = dataFixerBuilder.addSchema(1906, V1906::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var80, "Add POI Blocks", References.BLOCK_ENTITY));
      Schema var81 = dataFixerBuilder.addSchema(1909, V1909::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var81, "Add jigsaw", References.BLOCK_ENTITY));
      Schema var82 = dataFixerBuilder.addSchema(1911, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ChunkStatusFix2(var82, false));
      Schema var83 = dataFixerBuilder.addSchema(1917, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new CatTypeFix(var83, false));
      Schema var84 = dataFixerBuilder.addSchema(1918, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new VillagerDataFix(var84, "minecraft:villager"));
      dataFixerBuilder.addFixer(new VillagerDataFix(var84, "minecraft:zombie_villager"));
      Schema var85 = dataFixerBuilder.addSchema(1920, V1920::<init>);
      dataFixerBuilder.addFixer(new NewVillageFix(var85, false));
      dataFixerBuilder.addFixer(new AddNewChoices(var85, "Add campfire", References.BLOCK_ENTITY));
      Schema var86 = dataFixerBuilder.addSchema(1925, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new MapIdFix(var86, false));
      Schema var87 = dataFixerBuilder.addSchema(1928, V1928::<init>);
      dataFixerBuilder.addFixer(new EntityRavagerRenameFix(var87, true));
      dataFixerBuilder.addFixer(ItemRenameFix.create(var87, "Rename ravager egg item", (string) -> {
         return (String)EntityRavagerRenameFix.RENAMED_IDS.getOrDefault(string, string);
      }));
      Schema var88 = dataFixerBuilder.addSchema(1929, V1929::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var88, "Add Wandering Trader and Trader Llama", References.ENTITY));
      Schema var89 = dataFixerBuilder.addSchema(1931, V1931::<init>);
      dataFixerBuilder.addFixer(new AddNewChoices(var89, "Added Fox", References.ENTITY));
      Schema var90 = dataFixerBuilder.addSchema(1936, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OptionsAddTextBackgroundFix(var90, false));
      Schema var91 = dataFixerBuilder.addSchema(1946, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ReorganizePoi(var91, false));
      Schema var92 = dataFixerBuilder.addSchema(1948, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OminousBannerRenameFix(var92, false));
      Schema var93 = dataFixerBuilder.addSchema(1953, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new OminousBannerBlockEntityRenameFix(var93, false));
      Schema var94 = dataFixerBuilder.addSchema(1955, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new VillagerRebuildLevelAndXpFix(var94, false));
      dataFixerBuilder.addFixer(new ZombieVillagerRebuildXpFix(var94, false));
      Schema var95 = dataFixerBuilder.addSchema(1961, SAME_NAMESPACED);
      dataFixerBuilder.addFixer(new ChunkLightRemoveFix(var95, false));
   }
}
