package net.minecraft.util.datafix.fixes;

import com.google.common.collect.Maps;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFix;
import com.mojang.datafixers.DataFixUtils;
import com.mojang.datafixers.Dynamic;
import com.mojang.datafixers.TypeRewriteRule;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.schemas.Schema;
import com.mojang.datafixers.types.Type;
import com.mojang.datafixers.util.Either;
import com.mojang.datafixers.util.Pair;
import com.mojang.datafixers.util.Unit;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;
import net.minecraft.util.datafix.fixes.BlockStateData;
import net.minecraft.util.datafix.fixes.References;

public class EntityBlockStateFix extends DataFix {
   private static final Map MAP = (Map)DataFixUtils.make(Maps.newHashMap(), (hashMap) -> {
      hashMap.put("minecraft:air", Integer.valueOf(0));
      hashMap.put("minecraft:stone", Integer.valueOf(1));
      hashMap.put("minecraft:grass", Integer.valueOf(2));
      hashMap.put("minecraft:dirt", Integer.valueOf(3));
      hashMap.put("minecraft:cobblestone", Integer.valueOf(4));
      hashMap.put("minecraft:planks", Integer.valueOf(5));
      hashMap.put("minecraft:sapling", Integer.valueOf(6));
      hashMap.put("minecraft:bedrock", Integer.valueOf(7));
      hashMap.put("minecraft:flowing_water", Integer.valueOf(8));
      hashMap.put("minecraft:water", Integer.valueOf(9));
      hashMap.put("minecraft:flowing_lava", Integer.valueOf(10));
      hashMap.put("minecraft:lava", Integer.valueOf(11));
      hashMap.put("minecraft:sand", Integer.valueOf(12));
      hashMap.put("minecraft:gravel", Integer.valueOf(13));
      hashMap.put("minecraft:gold_ore", Integer.valueOf(14));
      hashMap.put("minecraft:iron_ore", Integer.valueOf(15));
      hashMap.put("minecraft:coal_ore", Integer.valueOf(16));
      hashMap.put("minecraft:log", Integer.valueOf(17));
      hashMap.put("minecraft:leaves", Integer.valueOf(18));
      hashMap.put("minecraft:sponge", Integer.valueOf(19));
      hashMap.put("minecraft:glass", Integer.valueOf(20));
      hashMap.put("minecraft:lapis_ore", Integer.valueOf(21));
      hashMap.put("minecraft:lapis_block", Integer.valueOf(22));
      hashMap.put("minecraft:dispenser", Integer.valueOf(23));
      hashMap.put("minecraft:sandstone", Integer.valueOf(24));
      hashMap.put("minecraft:noteblock", Integer.valueOf(25));
      hashMap.put("minecraft:bed", Integer.valueOf(26));
      hashMap.put("minecraft:golden_rail", Integer.valueOf(27));
      hashMap.put("minecraft:detector_rail", Integer.valueOf(28));
      hashMap.put("minecraft:sticky_piston", Integer.valueOf(29));
      hashMap.put("minecraft:web", Integer.valueOf(30));
      hashMap.put("minecraft:tallgrass", Integer.valueOf(31));
      hashMap.put("minecraft:deadbush", Integer.valueOf(32));
      hashMap.put("minecraft:piston", Integer.valueOf(33));
      hashMap.put("minecraft:piston_head", Integer.valueOf(34));
      hashMap.put("minecraft:wool", Integer.valueOf(35));
      hashMap.put("minecraft:piston_extension", Integer.valueOf(36));
      hashMap.put("minecraft:yellow_flower", Integer.valueOf(37));
      hashMap.put("minecraft:red_flower", Integer.valueOf(38));
      hashMap.put("minecraft:brown_mushroom", Integer.valueOf(39));
      hashMap.put("minecraft:red_mushroom", Integer.valueOf(40));
      hashMap.put("minecraft:gold_block", Integer.valueOf(41));
      hashMap.put("minecraft:iron_block", Integer.valueOf(42));
      hashMap.put("minecraft:double_stone_slab", Integer.valueOf(43));
      hashMap.put("minecraft:stone_slab", Integer.valueOf(44));
      hashMap.put("minecraft:brick_block", Integer.valueOf(45));
      hashMap.put("minecraft:tnt", Integer.valueOf(46));
      hashMap.put("minecraft:bookshelf", Integer.valueOf(47));
      hashMap.put("minecraft:mossy_cobblestone", Integer.valueOf(48));
      hashMap.put("minecraft:obsidian", Integer.valueOf(49));
      hashMap.put("minecraft:torch", Integer.valueOf(50));
      hashMap.put("minecraft:fire", Integer.valueOf(51));
      hashMap.put("minecraft:mob_spawner", Integer.valueOf(52));
      hashMap.put("minecraft:oak_stairs", Integer.valueOf(53));
      hashMap.put("minecraft:chest", Integer.valueOf(54));
      hashMap.put("minecraft:redstone_wire", Integer.valueOf(55));
      hashMap.put("minecraft:diamond_ore", Integer.valueOf(56));
      hashMap.put("minecraft:diamond_block", Integer.valueOf(57));
      hashMap.put("minecraft:crafting_table", Integer.valueOf(58));
      hashMap.put("minecraft:wheat", Integer.valueOf(59));
      hashMap.put("minecraft:farmland", Integer.valueOf(60));
      hashMap.put("minecraft:furnace", Integer.valueOf(61));
      hashMap.put("minecraft:lit_furnace", Integer.valueOf(62));
      hashMap.put("minecraft:standing_sign", Integer.valueOf(63));
      hashMap.put("minecraft:wooden_door", Integer.valueOf(64));
      hashMap.put("minecraft:ladder", Integer.valueOf(65));
      hashMap.put("minecraft:rail", Integer.valueOf(66));
      hashMap.put("minecraft:stone_stairs", Integer.valueOf(67));
      hashMap.put("minecraft:wall_sign", Integer.valueOf(68));
      hashMap.put("minecraft:lever", Integer.valueOf(69));
      hashMap.put("minecraft:stone_pressure_plate", Integer.valueOf(70));
      hashMap.put("minecraft:iron_door", Integer.valueOf(71));
      hashMap.put("minecraft:wooden_pressure_plate", Integer.valueOf(72));
      hashMap.put("minecraft:redstone_ore", Integer.valueOf(73));
      hashMap.put("minecraft:lit_redstone_ore", Integer.valueOf(74));
      hashMap.put("minecraft:unlit_redstone_torch", Integer.valueOf(75));
      hashMap.put("minecraft:redstone_torch", Integer.valueOf(76));
      hashMap.put("minecraft:stone_button", Integer.valueOf(77));
      hashMap.put("minecraft:snow_layer", Integer.valueOf(78));
      hashMap.put("minecraft:ice", Integer.valueOf(79));
      hashMap.put("minecraft:snow", Integer.valueOf(80));
      hashMap.put("minecraft:cactus", Integer.valueOf(81));
      hashMap.put("minecraft:clay", Integer.valueOf(82));
      hashMap.put("minecraft:reeds", Integer.valueOf(83));
      hashMap.put("minecraft:jukebox", Integer.valueOf(84));
      hashMap.put("minecraft:fence", Integer.valueOf(85));
      hashMap.put("minecraft:pumpkin", Integer.valueOf(86));
      hashMap.put("minecraft:netherrack", Integer.valueOf(87));
      hashMap.put("minecraft:soul_sand", Integer.valueOf(88));
      hashMap.put("minecraft:glowstone", Integer.valueOf(89));
      hashMap.put("minecraft:portal", Integer.valueOf(90));
      hashMap.put("minecraft:lit_pumpkin", Integer.valueOf(91));
      hashMap.put("minecraft:cake", Integer.valueOf(92));
      hashMap.put("minecraft:unpowered_repeater", Integer.valueOf(93));
      hashMap.put("minecraft:powered_repeater", Integer.valueOf(94));
      hashMap.put("minecraft:stained_glass", Integer.valueOf(95));
      hashMap.put("minecraft:trapdoor", Integer.valueOf(96));
      hashMap.put("minecraft:monster_egg", Integer.valueOf(97));
      hashMap.put("minecraft:stonebrick", Integer.valueOf(98));
      hashMap.put("minecraft:brown_mushroom_block", Integer.valueOf(99));
      hashMap.put("minecraft:red_mushroom_block", Integer.valueOf(100));
      hashMap.put("minecraft:iron_bars", Integer.valueOf(101));
      hashMap.put("minecraft:glass_pane", Integer.valueOf(102));
      hashMap.put("minecraft:melon_block", Integer.valueOf(103));
      hashMap.put("minecraft:pumpkin_stem", Integer.valueOf(104));
      hashMap.put("minecraft:melon_stem", Integer.valueOf(105));
      hashMap.put("minecraft:vine", Integer.valueOf(106));
      hashMap.put("minecraft:fence_gate", Integer.valueOf(107));
      hashMap.put("minecraft:brick_stairs", Integer.valueOf(108));
      hashMap.put("minecraft:stone_brick_stairs", Integer.valueOf(109));
      hashMap.put("minecraft:mycelium", Integer.valueOf(110));
      hashMap.put("minecraft:waterlily", Integer.valueOf(111));
      hashMap.put("minecraft:nether_brick", Integer.valueOf(112));
      hashMap.put("minecraft:nether_brick_fence", Integer.valueOf(113));
      hashMap.put("minecraft:nether_brick_stairs", Integer.valueOf(114));
      hashMap.put("minecraft:nether_wart", Integer.valueOf(115));
      hashMap.put("minecraft:enchanting_table", Integer.valueOf(116));
      hashMap.put("minecraft:brewing_stand", Integer.valueOf(117));
      hashMap.put("minecraft:cauldron", Integer.valueOf(118));
      hashMap.put("minecraft:end_portal", Integer.valueOf(119));
      hashMap.put("minecraft:end_portal_frame", Integer.valueOf(120));
      hashMap.put("minecraft:end_stone", Integer.valueOf(121));
      hashMap.put("minecraft:dragon_egg", Integer.valueOf(122));
      hashMap.put("minecraft:redstone_lamp", Integer.valueOf(123));
      hashMap.put("minecraft:lit_redstone_lamp", Integer.valueOf(124));
      hashMap.put("minecraft:double_wooden_slab", Integer.valueOf(125));
      hashMap.put("minecraft:wooden_slab", Integer.valueOf(126));
      hashMap.put("minecraft:cocoa", Integer.valueOf(127));
      hashMap.put("minecraft:sandstone_stairs", Integer.valueOf(128));
      hashMap.put("minecraft:emerald_ore", Integer.valueOf(129));
      hashMap.put("minecraft:ender_chest", Integer.valueOf(130));
      hashMap.put("minecraft:tripwire_hook", Integer.valueOf(131));
      hashMap.put("minecraft:tripwire", Integer.valueOf(132));
      hashMap.put("minecraft:emerald_block", Integer.valueOf(133));
      hashMap.put("minecraft:spruce_stairs", Integer.valueOf(134));
      hashMap.put("minecraft:birch_stairs", Integer.valueOf(135));
      hashMap.put("minecraft:jungle_stairs", Integer.valueOf(136));
      hashMap.put("minecraft:command_block", Integer.valueOf(137));
      hashMap.put("minecraft:beacon", Integer.valueOf(138));
      hashMap.put("minecraft:cobblestone_wall", Integer.valueOf(139));
      hashMap.put("minecraft:flower_pot", Integer.valueOf(140));
      hashMap.put("minecraft:carrots", Integer.valueOf(141));
      hashMap.put("minecraft:potatoes", Integer.valueOf(142));
      hashMap.put("minecraft:wooden_button", Integer.valueOf(143));
      hashMap.put("minecraft:skull", Integer.valueOf(144));
      hashMap.put("minecraft:anvil", Integer.valueOf(145));
      hashMap.put("minecraft:trapped_chest", Integer.valueOf(146));
      hashMap.put("minecraft:light_weighted_pressure_plate", Integer.valueOf(147));
      hashMap.put("minecraft:heavy_weighted_pressure_plate", Integer.valueOf(148));
      hashMap.put("minecraft:unpowered_comparator", Integer.valueOf(149));
      hashMap.put("minecraft:powered_comparator", Integer.valueOf(150));
      hashMap.put("minecraft:daylight_detector", Integer.valueOf(151));
      hashMap.put("minecraft:redstone_block", Integer.valueOf(152));
      hashMap.put("minecraft:quartz_ore", Integer.valueOf(153));
      hashMap.put("minecraft:hopper", Integer.valueOf(154));
      hashMap.put("minecraft:quartz_block", Integer.valueOf(155));
      hashMap.put("minecraft:quartz_stairs", Integer.valueOf(156));
      hashMap.put("minecraft:activator_rail", Integer.valueOf(157));
      hashMap.put("minecraft:dropper", Integer.valueOf(158));
      hashMap.put("minecraft:stained_hardened_clay", Integer.valueOf(159));
      hashMap.put("minecraft:stained_glass_pane", Integer.valueOf(160));
      hashMap.put("minecraft:leaves2", Integer.valueOf(161));
      hashMap.put("minecraft:log2", Integer.valueOf(162));
      hashMap.put("minecraft:acacia_stairs", Integer.valueOf(163));
      hashMap.put("minecraft:dark_oak_stairs", Integer.valueOf(164));
      hashMap.put("minecraft:slime", Integer.valueOf(165));
      hashMap.put("minecraft:barrier", Integer.valueOf(166));
      hashMap.put("minecraft:iron_trapdoor", Integer.valueOf(167));
      hashMap.put("minecraft:prismarine", Integer.valueOf(168));
      hashMap.put("minecraft:sea_lantern", Integer.valueOf(169));
      hashMap.put("minecraft:hay_block", Integer.valueOf(170));
      hashMap.put("minecraft:carpet", Integer.valueOf(171));
      hashMap.put("minecraft:hardened_clay", Integer.valueOf(172));
      hashMap.put("minecraft:coal_block", Integer.valueOf(173));
      hashMap.put("minecraft:packed_ice", Integer.valueOf(174));
      hashMap.put("minecraft:double_plant", Integer.valueOf(175));
      hashMap.put("minecraft:standing_banner", Integer.valueOf(176));
      hashMap.put("minecraft:wall_banner", Integer.valueOf(177));
      hashMap.put("minecraft:daylight_detector_inverted", Integer.valueOf(178));
      hashMap.put("minecraft:red_sandstone", Integer.valueOf(179));
      hashMap.put("minecraft:red_sandstone_stairs", Integer.valueOf(180));
      hashMap.put("minecraft:double_stone_slab2", Integer.valueOf(181));
      hashMap.put("minecraft:stone_slab2", Integer.valueOf(182));
      hashMap.put("minecraft:spruce_fence_gate", Integer.valueOf(183));
      hashMap.put("minecraft:birch_fence_gate", Integer.valueOf(184));
      hashMap.put("minecraft:jungle_fence_gate", Integer.valueOf(185));
      hashMap.put("minecraft:dark_oak_fence_gate", Integer.valueOf(186));
      hashMap.put("minecraft:acacia_fence_gate", Integer.valueOf(187));
      hashMap.put("minecraft:spruce_fence", Integer.valueOf(188));
      hashMap.put("minecraft:birch_fence", Integer.valueOf(189));
      hashMap.put("minecraft:jungle_fence", Integer.valueOf(190));
      hashMap.put("minecraft:dark_oak_fence", Integer.valueOf(191));
      hashMap.put("minecraft:acacia_fence", Integer.valueOf(192));
      hashMap.put("minecraft:spruce_door", Integer.valueOf(193));
      hashMap.put("minecraft:birch_door", Integer.valueOf(194));
      hashMap.put("minecraft:jungle_door", Integer.valueOf(195));
      hashMap.put("minecraft:acacia_door", Integer.valueOf(196));
      hashMap.put("minecraft:dark_oak_door", Integer.valueOf(197));
      hashMap.put("minecraft:end_rod", Integer.valueOf(198));
      hashMap.put("minecraft:chorus_plant", Integer.valueOf(199));
      hashMap.put("minecraft:chorus_flower", Integer.valueOf(200));
      hashMap.put("minecraft:purpur_block", Integer.valueOf(201));
      hashMap.put("minecraft:purpur_pillar", Integer.valueOf(202));
      hashMap.put("minecraft:purpur_stairs", Integer.valueOf(203));
      hashMap.put("minecraft:purpur_double_slab", Integer.valueOf(204));
      hashMap.put("minecraft:purpur_slab", Integer.valueOf(205));
      hashMap.put("minecraft:end_bricks", Integer.valueOf(206));
      hashMap.put("minecraft:beetroots", Integer.valueOf(207));
      hashMap.put("minecraft:grass_path", Integer.valueOf(208));
      hashMap.put("minecraft:end_gateway", Integer.valueOf(209));
      hashMap.put("minecraft:repeating_command_block", Integer.valueOf(210));
      hashMap.put("minecraft:chain_command_block", Integer.valueOf(211));
      hashMap.put("minecraft:frosted_ice", Integer.valueOf(212));
      hashMap.put("minecraft:magma", Integer.valueOf(213));
      hashMap.put("minecraft:nether_wart_block", Integer.valueOf(214));
      hashMap.put("minecraft:red_nether_brick", Integer.valueOf(215));
      hashMap.put("minecraft:bone_block", Integer.valueOf(216));
      hashMap.put("minecraft:structure_void", Integer.valueOf(217));
      hashMap.put("minecraft:observer", Integer.valueOf(218));
      hashMap.put("minecraft:white_shulker_box", Integer.valueOf(219));
      hashMap.put("minecraft:orange_shulker_box", Integer.valueOf(220));
      hashMap.put("minecraft:magenta_shulker_box", Integer.valueOf(221));
      hashMap.put("minecraft:light_blue_shulker_box", Integer.valueOf(222));
      hashMap.put("minecraft:yellow_shulker_box", Integer.valueOf(223));
      hashMap.put("minecraft:lime_shulker_box", Integer.valueOf(224));
      hashMap.put("minecraft:pink_shulker_box", Integer.valueOf(225));
      hashMap.put("minecraft:gray_shulker_box", Integer.valueOf(226));
      hashMap.put("minecraft:silver_shulker_box", Integer.valueOf(227));
      hashMap.put("minecraft:cyan_shulker_box", Integer.valueOf(228));
      hashMap.put("minecraft:purple_shulker_box", Integer.valueOf(229));
      hashMap.put("minecraft:blue_shulker_box", Integer.valueOf(230));
      hashMap.put("minecraft:brown_shulker_box", Integer.valueOf(231));
      hashMap.put("minecraft:green_shulker_box", Integer.valueOf(232));
      hashMap.put("minecraft:red_shulker_box", Integer.valueOf(233));
      hashMap.put("minecraft:black_shulker_box", Integer.valueOf(234));
      hashMap.put("minecraft:white_glazed_terracotta", Integer.valueOf(235));
      hashMap.put("minecraft:orange_glazed_terracotta", Integer.valueOf(236));
      hashMap.put("minecraft:magenta_glazed_terracotta", Integer.valueOf(237));
      hashMap.put("minecraft:light_blue_glazed_terracotta", Integer.valueOf(238));
      hashMap.put("minecraft:yellow_glazed_terracotta", Integer.valueOf(239));
      hashMap.put("minecraft:lime_glazed_terracotta", Integer.valueOf(240));
      hashMap.put("minecraft:pink_glazed_terracotta", Integer.valueOf(241));
      hashMap.put("minecraft:gray_glazed_terracotta", Integer.valueOf(242));
      hashMap.put("minecraft:silver_glazed_terracotta", Integer.valueOf(243));
      hashMap.put("minecraft:cyan_glazed_terracotta", Integer.valueOf(244));
      hashMap.put("minecraft:purple_glazed_terracotta", Integer.valueOf(245));
      hashMap.put("minecraft:blue_glazed_terracotta", Integer.valueOf(246));
      hashMap.put("minecraft:brown_glazed_terracotta", Integer.valueOf(247));
      hashMap.put("minecraft:green_glazed_terracotta", Integer.valueOf(248));
      hashMap.put("minecraft:red_glazed_terracotta", Integer.valueOf(249));
      hashMap.put("minecraft:black_glazed_terracotta", Integer.valueOf(250));
      hashMap.put("minecraft:concrete", Integer.valueOf(251));
      hashMap.put("minecraft:concrete_powder", Integer.valueOf(252));
      hashMap.put("minecraft:structure_block", Integer.valueOf(255));
   });

   public EntityBlockStateFix(Schema schema, boolean var2) {
      super(schema, var2);
   }

   public static int getBlockId(String string) {
      Integer var1 = (Integer)MAP.get(string);
      return var1 == null?0:var1.intValue();
   }

   public TypeRewriteRule makeRule() {
      Schema var1 = this.getInputSchema();
      Schema var2 = this.getOutputSchema();
      Function<Typed<?>, Typed<?>> var3 = (typed) -> {
         return this.updateBlockToBlockState(typed, "DisplayTile", "DisplayData", "DisplayState");
      };
      Function<Typed<?>, Typed<?>> var4 = (typed) -> {
         return this.updateBlockToBlockState(typed, "inTile", "inData", "inBlockState");
      };
      Type<Pair<Either<Pair<String, Either<Integer, String>>, Unit>, Dynamic<?>>> var5 = DSL.and(DSL.optional(DSL.field("inTile", DSL.named(References.BLOCK_NAME.typeName(), DSL.or(DSL.intType(), DSL.namespacedString())))), DSL.remainderType());
      Function<Typed<?>, Typed<?>> var6 = (var1) -> {
         return var1.update(var5.finder(), DSL.remainderType(), Pair::getSecond);
      };
      return this.fixTypeEverywhereTyped("EntityBlockStateFix", var1.getType(References.ENTITY), var2.getType(References.ENTITY), (var4x) -> {
         var4x = this.updateEntity(var4x, "minecraft:falling_block", this::updateFallingBlock);
         var4x = this.updateEntity(var4x, "minecraft:enderman", (typed) -> {
            return this.updateBlockToBlockState(typed, "carried", "carriedData", "carriedBlockState");
         });
         var4x = this.updateEntity(var4x, "minecraft:arrow", var4);
         var4x = this.updateEntity(var4x, "minecraft:spectral_arrow", var4);
         var4x = this.updateEntity(var4x, "minecraft:egg", var6);
         var4x = this.updateEntity(var4x, "minecraft:ender_pearl", var6);
         var4x = this.updateEntity(var4x, "minecraft:fireball", var6);
         var4x = this.updateEntity(var4x, "minecraft:potion", var6);
         var4x = this.updateEntity(var4x, "minecraft:small_fireball", var6);
         var4x = this.updateEntity(var4x, "minecraft:snowball", var6);
         var4x = this.updateEntity(var4x, "minecraft:wither_skull", var6);
         var4x = this.updateEntity(var4x, "minecraft:xp_bottle", var6);
         var4x = this.updateEntity(var4x, "minecraft:commandblock_minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:chest_minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:furnace_minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:tnt_minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:hopper_minecart", var3);
         var4x = this.updateEntity(var4x, "minecraft:spawner_minecart", var3);
         return var4x;
      });
   }

   private Typed updateFallingBlock(Typed typed) {
      Type<Either<Pair<String, Either<Integer, String>>, Unit>> var2 = DSL.optional(DSL.field("Block", DSL.named(References.BLOCK_NAME.typeName(), DSL.or(DSL.intType(), DSL.namespacedString()))));
      Type<Either<Pair<String, Dynamic<?>>, Unit>> var3 = DSL.optional(DSL.field("BlockState", DSL.named(References.BLOCK_STATE.typeName(), DSL.remainderType())));
      Dynamic<?> var4 = (Dynamic)typed.get(DSL.remainderFinder());
      return typed.update(var2.finder(), var3, (var1) -> {
         int var2 = ((Integer)var1.map((pair) -> {
            return (Integer)((Either)pair.getSecond()).map((integer) -> {
               return integer;
            }, EntityBlockStateFix::getBlockId);
         }, (unit) -> {
            Optional<Number> var2 = var4.get("TileID").asNumber();
            return (Integer)var2.map(Number::intValue).orElseGet(() -> {
               return Integer.valueOf(var4.get("Tile").asByte((byte)0) & 255);
            });
         })).intValue();
         int var3 = var4.get("Data").asInt(0) & 15;
         return Either.left(Pair.of(References.BLOCK_STATE.typeName(), BlockStateData.getTag(var2 << 4 | var3)));
      }).set(DSL.remainderFinder(), var4.remove("Data").remove("TileID").remove("Tile"));
   }

   private Typed updateBlockToBlockState(Typed var1, String var2, String var3, String var4) {
      Type<Pair<String, Either<Integer, String>>> var5 = DSL.field(var2, DSL.named(References.BLOCK_NAME.typeName(), DSL.or(DSL.intType(), DSL.namespacedString())));
      Type<Pair<String, Dynamic<?>>> var6 = DSL.field(var4, DSL.named(References.BLOCK_STATE.typeName(), DSL.remainderType()));
      Dynamic<?> var7 = (Dynamic)var1.getOrCreate(DSL.remainderFinder());
      return var1.update(var5.finder(), var6, (var2) -> {
         int var3 = ((Integer)((Either)var2.getSecond()).map((integer) -> {
            return integer;
         }, EntityBlockStateFix::getBlockId)).intValue();
         int var4 = var7.get(var3).asInt(0) & 15;
         return Pair.of(References.BLOCK_STATE.typeName(), BlockStateData.getTag(var3 << 4 | var4));
      }).set(DSL.remainderFinder(), var7.remove(var3));
   }

   private Typed updateEntity(Typed var1, String string, Function function) {
      Type<?> var4 = this.getInputSchema().getChoiceType(References.ENTITY, string);
      Type<?> var5 = this.getOutputSchema().getChoiceType(References.ENTITY, string);
      return var1.updateTyped(DSL.namedChoice(string, var4), var5, function);
   }
}
